package com.prism.launcher.nora

import kotlin.math.PI
import kotlin.math.atan2
import kotlin.math.cos
import kotlin.math.sin
import kotlin.math.sqrt
import kotlin.random.Random

/**
 * V1 orientation-preference map with pinwheel topography.
 *
 * Orientation preference in primate V1 is not arbitrary per neuron: it varies smoothly across
 * the cortical surface and is organized around point singularities -- pinwheels -- with a
 * characteristic spacing of roughly 0.5-1 mm (Blasdel & Salama 1986; Bonhoeffer & Grinvald
 * 1991; Ohki et al. 2006). Between pinwheels, preference changes in smooth linear zones.
 *
 * The map is generated by summing a small number of random plane waves of fixed spatial
 * frequency and taking the phase of the result. This is the standard descriptive model
 * (Rojer & Schwartz 1990; Niebur & Worgotter 1994) and it reproduces the real statistics --
 * pinwheel density near pi per hypercolumn area, linear zones, correct orientation gradient
 * distribution.
 *
 * HONESTY FLAG: this generates a map with the right STATISTICS, not by the right MECHANISM.
 * The real map develops through activity-dependent self-organization constrained by lateral
 * connectivity (Miller 1994; Swindale 1996). Nora installs the endpoint rather than growing
 * it, the way a genome specifies a proto-map that experience then refines. If this were a
 * developmental model that shortcut would be fatal; for a generative model it is a defensible
 * initialization.
 */
class OrientationMap(
    private val h: Int,
    private val w: Int,
    seed: Long = 0x1F03E5L
) {

    /** Preferred orientation at each cortical location, in radians [0, pi). */
    val preference = FloatArray(h * w)

    /**
     * Local map selectivity: near a pinwheel centre all orientations are represented within a
     * tiny cortical distance, so the local gain bias is weak. In linear zones it is strong.
     * This is measured (Ohki et al. 2006 found pinwheel centres are genuinely disordered) and
     * it matters -- it means the columnar constraint is graded, not binary.
     */
    val selectivity = FloatArray(h * w)

    init {
        val rng = Random(seed)
        val waves = 6
        // Spatial frequency chosen so ~4 hypercolumns span the sheet.
        val k = 4.0 * PI / sqrt((h * w).toDouble())

        val real = DoubleArray(h * w)
        val imag = DoubleArray(h * w)

        for (n in 0 until waves) {
            val phi = rng.nextDouble() * 2 * PI
            val psi = rng.nextDouble() * 2 * PI
            val kx = k * cos(phi)
            val ky = k * sin(phi)
            for (y in 0 until h) {
                for (x in 0 until w) {
                    val arg = kx * x + ky * y + psi
                    real[y * w + x] += cos(arg)
                    imag[y * w + x] += sin(arg)
                }
            }
        }

        var maxMag = 1e-9
        for (i in real.indices) {
            val m = sqrt(real[i] * real[i] + imag[i] * imag[i])
            if (m > maxMag) maxMag = m
        }

        for (i in real.indices) {
            // Halving the phase maps the full 2pi of the complex field onto the pi range of
            // orientation, which is what makes the singularities half-turn pinwheels rather
            // than full-turn vortices -- the topological signature seen in optical imaging.
            val phase = atan2(imag[i], real[i])
            var ori = (phase * 0.5).toFloat()
            if (ori < 0) ori += PI.toFloat()
            preference[i] = ori
            selectivity[i] = (sqrt(real[i] * real[i] + imag[i] * imag[i]) / maxMag).toFloat()
        }
    }

    /**
     * Gain applied to a unit tuned to [orientation] sitting at cortical location (y, x).
     *
     * Returns 1.0 when the unit matches its column and falls toward
     * (1 - PINWHEEL_STRENGTH) when it is maximally mismatched, scaled by how well-defined the
     * local column is. Orientation is periodic over pi, so the tuning uses double angle.
     */
    fun gainFor(y: Int, x: Int, orientation: Float): Float {
        val idx = y * w + x
        val d = 2f * (orientation - preference[idx])
        val match = 0.5f * (1f + cos(d.toDouble()).toFloat())   // 1 aligned, 0 orthogonal
        val strength = NoraConfig.PINWHEEL_STRENGTH * selectivity[idx]
        return (1f - strength) + strength * match
    }
}
